"""Added Tables

Revision ID: df7400c36888
Revises: 05007d2d1afb
Create Date: 2021-10-29 07:24:28.131066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df7400c36888'
down_revision = '05007d2d1afb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gender',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('actor',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('dob', sa.DateTime(), nullable=False),
                    sa.Column('gender_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['gender_id'], ['gender.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('casting',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('actor_id', sa.Integer(), nullable=False),
                    sa.Column('movie_id', sa.Integer(), nullable=False),
                    sa.Column('casting_date', sa.DateTime(), nullable=False),
                    sa.Column('recast_yn', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], ),
                    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('actor_id', 'movie_id',
                                        'casting_date', name='UX_actor_movie_date')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('casting')
    op.drop_table('actor')
    op.drop_table('gender')
    # ### end Alembic commands ###
